
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,...........A.....R|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z....r...|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,..................|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()
joypad.setfrommnemonicstr("|..|    0,    0,.........Z...d....|")
emu.frameadvance()